### ISSUE TITLE
Support for .aab extension in app live upload

### ISSUE THREAD

**Issue by ShawnCholeva** [browserstack/browserstack-fastlane-plugin#14] opened 2020-05-29 16:01 UTC
I noticed the plugin only supports the following extensions

```SUPPORTED_FILE_EXTENSIONS = ["apk", "ipa"]```

Browserstack seems to be accepting aab files now as well, could we get this added to the supported file extensions?

**Comment by dharmendrajha** [comment] 2020-05-29 20:06
This feature is indeed a part of our roadmap and will be available soon.

**Comment by colog10** [comment] 2020-08-24 20:59
Hey there are any update here? =)

**Comment by R-eehan** [comment] 2020-08-24 21:39
Hey @colog10,  this is still being worked upon. We will be sure to notify you once this is available!

**Comment by besologic** [comment] 2020-11-04 21:20
👋🏼 Hello! Any updates on being able to upload AAB's to Browserstack?

**Comment by shawnlobo96** [comment] 2020-11-04 21:59
Hey @besologic 👋

Uploading .aab is supported via the UI. Uploading via the plugin is still being worked upon. We'll be sure to notify you once it's done :)

**Comment by leezumstein** [comment] 2021-03-26 16:58
Any update on support for uploading aab?  The google play store will be deprecating apk uploads starting in August 2021, would prefer if our automated testing was executed against the same build type being sent to the play store.

**Comment by vsukhomlinov** [comment] 2021-04-15 18:07
Hi @shawnlobo96 ,

It seems like AAB files can be uploaded via API as well. Do you think that adding one more extension to the SUPPORTED_FILE_EXTENSIONS as all we need here?

**Comment by dharmendrajha** [comment] 2021-04-15 19:42
Hey @vsukhomlinov, the team is working towards adding support for AAB files upload via the plugin. We'll be sure to notify you once it's done.

**Comment by Zemotacqy** [comment] 2021-04-22 14:19
The issue is solved via #16. Closing this.

**Closed** 2021-04-22 14:19 UTC
